- hosts: localhost
  become: true
  tasks:
  - name: install basic utilities
    apt:
      package:
      - htop
      - tilix
      - git
      - dolphin
      - konsole		# for dolphin
      - ark		# for dolphin
      - kgpg
      - net-tools
