- hosts: localhost
  become: true
  tasks:
  - name: install basic utilities
    apt:
      package:
      - htop
      - tilix
      - git
      - dolphin
      - konsole		# for dolphin
      - ark		# for dolphin
      - kgpg
      - net-tools
  - name: install synaptic
    apt:
      package:
      - synaptic
      - apt-xapian-index
    shell: update-apt-xapian-index -vf
      creates: /var/lib/apt-xapian-index/update-lock

