- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        upgrade: yes
      changed_when: False
    - name: install roles
      shell:
        cmd: ansible-galaxy install -r requirements.yml
  tasks:
    - include: tasks/packages.yml
    - include: tasks/nodejs.yml
    - include: tasks/docker.yml
    - include: tasks/jdk.yml
    - include: tasks/toolbox.yml
    - include: tasks/sbt.yml
    - include: tasks/scala.yml

