- name: install docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
- name: add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
- name: install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest
 
