- name: install JDK
  become: true
  apt:
    name:
      - default-jdk
      - default-jdk-headless
      - default-jdk-doc
      - openjdk-11-source
    state: present
- debug:
    msg: 'Jave API: file:///usr/share/doc/openjdk-11-doc/api/index.html'

