- name: determine unprivileged user
  command: ls /home
  register: user
- stat:
    path: /home/{{user.stdout}}/.ssh
  register: ssh_folder
  changed_when: false
- name: create .ssh folder
  file:
    path: /home/{{user.stdout}}/.ssh
    owner: '{{user.stdout}}'
    group: '{{user.stdout}}'
    state: directory
  when: ssh_folder.stat.isdir is undefined
- name: generate SSH keys
  openssh_keypair:
    type: ed25519
    path: /home/{{user.stdout}}/.ssh/id_rsa
    owner: '{{user.stdout}}'
    group: '{{user.stdout}}'
  when: ssh_folder.stat.isdir is undefined

