- name: determine unprivileged user
  command: ls /home
  register: user
- name: create .ssh folder
  file:
    path: /home/{{user.stdout}}/.ssh
    owner: '{{user.stdout}}'
    group: '{{user.stdout}}'
    state: directory
- name: generate SSH keys
  openssh_keypair:
    type: ed25519
    path: /home/{{user.stdout}}/.ssh/id_rsa
    owner: '{{user.stdout}}'
    group: '{{user.stdout}}'
