- name: install basic packages
  apt:
    package:
    - htop
    - tilix
    - git
    - dolphin
    - konsole		# for dolphin
    - ark		# for dolphin
    - kgpg
    - net-tools
    - synaptic
    - apt-xapian-index	# for synaptic
    - nginx
    - python-pip
    - ansible
- name: create synaptic index
  shell: update-apt-xapian-index -vf
  args:
    creates: /var/lib/apt-xapian-index/update-lock

