- name: check if role installed
  command: ansible-galaxy role info --offline webarchitect609.jet_brains_toolbox
  register: ansible_galaxy_role
  changed_when: ansible_galaxy_role.stdout.find('installed') == -1
- name: install roles
  command: ansible-galaxy install -r requirements.yml
  when: ansible_galaxy_role.stdout.find('installed') == -1

