- name: install support for Scala Native
  apt:
    package:
    - clang
    - libunwind-dev
    - libgc-dev
    - libre2-dev
- name: install scala 2.13.2
  apt:
    deb: http://www.scala-lang.org/files/archive/scala-2.13.2.deb
- name: set permissions for docs
  file:
    path: /usr/share/doc/scala/api/scala-library
    state: directory
    recurse: yes
    mode: a+rwx

