- name: install support for Scala Native
  apt:
    package:
    - clang
    - libunwind-dev
    - libgc-dev
    - libre2-dev
- name: install scala 2.13.2
  apt:
    deb: http://www.scala-lang.org/files/archive/scala-2.13.2.deb
#- name: Unarchive Scala API docs
#  unarchive:
#    src: http://www.scala-lang.org/files/archive/scala-docs-2.13.2.zip
#    dest: /usr/local/bin
#    remote_src: yes

