- name: install support for Scala Native
  apt:
    package:
    - clang
    - libunwind-dev
    - libgc-dev
    - libre2-dev
- name: Check if package 'scala' is installed
  command: dpkg-query -W scala
  register: scala_check_deb
  failed_when: scala_check_deb.rc > 1
  changed_when: scala_check_deb.rc == 1
- name: install scala 2.13.3
  apt:
    deb: http://www.scala-lang.org/files/archive/scala-2.13.3.deb
  when: scala_check_deb.rc == 1
- name: set permissions for docs
  file:
    path: /usr/share/doc/scala/api/scala-library
    state: directory
    recurse: yes
    mode: a+rwx
  when: scala_check_deb.rc == 1
- debug:
    msg: 'Scala API: file:///usr/share/doc/scala/api/scala-library/index.html'

